services:
  watchcat:
    build: .
    # image: watchcat
    container_name: watchcat
    volumes:
      - ./:/app
    working_dir: /app
    command: python3 live2.py
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # 하나의 로그 파일 최대 크기
        max-file: "5"      # 최대 파일 수

  updater:
    build: .
    container_name: watchcat-updater
    volumes:
      - ./:/app
    working_dir: /app
    command: python3 updater.py
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # 하나의 로그 파일 최대 크기
        max-file: "5"      # 최대 파일 수
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=watchcat-token
      - INFLUXDB_ORG=watchcat_org
      - INFLUXDB_BUCKET=watchcat

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=watchcat_org
      - DOCKER_INFLUXDB_INIT_BUCKET=watchcat
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=watchcat-token

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  influxdb-data:
  grafana-storage: