services:
  watchcat:
    # image: watchcat
    build: .
    env_file:
      - .env
    container_name: watchcat
    volumes:
      - ./:/app
    working_dir: /app
    command: python3 live.py
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # 하나의 로그 파일 최대 크기
        max-file: "5"      # 최대 파일 수
    networks:
      - watchcat-net

  updater:
    build: .
    container_name: updater
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
    command: python3 -u stocker/updater.py
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - watchcat-net


  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=watchcat_org
      - DOCKER_INFLUXDB_INIT_BUCKET=watchcat
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=watchcat-token
    networks:
      - watchcat-net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - watchcat-net

  db:
    image: postgis/postgis:15-3.3  # PostgreSQL 15 + PostGIS 3.3
    container_name: postgis
    environment:
      POSTGRES_DB: gisdb
      POSTGRES_USER: mcesos
      POSTGRES_PASSWORD: mcesos2024@
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - watchcat-net

volumes:
  influxdb-data:
  grafana-storage:
  pgdata:

networks:
  watchcat-net:
    name: watchcat-net
    driver: bridge