FROM python:3.11-slim

# 시스템 패키지 설치
RUN apt-get update && \
    apt-get install -y gcc libpq-dev curl && \
    pip install poetry

# 작업 디렉토리
WORKDIR /app

# 의존성 정의 복사 및 설치
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false \
 && poetry install --no-root

# 나중에 전체 코드 복사
COPY . .